// <auto-generated />
namespace PhotoG.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _06072016 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_06072016));
        
        string IMigrationMetadata.Id
        {
            get { return "201606070925445_06.07.2016"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
